apiVersion: v2
name: hasura
description: Hasura GraphQL Engine
type: application
version: 1.1.7
appVersion: v2.18.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
keywords:
  - hasura
  - graphql
  - postgresql
