apiVersion: v2
name: hasura
description: Hasura GraphQL Engine
type: application
version: 1.1.7
appVersion: v2.0.9
dependencies:
  - name: common
    version: 1.9.0
    repository: 'https://charts.bitnami.com/bitnami'
keywords:
  - hasura
  - graphql
  - postgresql
